config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :users, only: [:show] do
    resources :registered_applications,  except: [:index ]
  end
  
  namespace :api, defaults: { format: :json } do
    resources :events, only: [:create]
  end
    
  authenticated :users do
    root to: 'users#show' , as: :authenticated_root
  end 
  
  get 'welcome/index'

  get 'welcome/about'
  
  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
  
  validates :name, presence: true
  
  
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy
  
  
   default_scope { order('updated_at DESC') }
   
   def event_for(registered_application)
     events.where(registered_application.id).first
   end
   
   
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :registered_applications, dependent: :destroy
  has_many :events
  
  attr_accessor :sign_in
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates_uniqueness_of :username, case_sensitive: false
  validates_presence_of   :username
  validates_format_of     :username, :with => /\A[A-Za-z\d]([-\w]{,498}[A-Za-z\d])?\z/i
  
  validates_presence_of   :password_confirmation
  
  validate :validate_username
  
  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
  
  
  def sign_in=(sign_in)
    @sign_in = sign_in
  end


  def sign_in
    @sign_in || self.username || self.email
  end
  
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if sign_in = conditions.delete(:sign_in)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => sign_in }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions).first
    end
  end
  
  
  def registered_for(app)
    registered_applications.where(app.id).first
  end

end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
    skip_before_action :verify_authenticity_token
    
    respond_to :json


    def create
        registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
        
        if registered_application
            event = registered_application.events.build(event_params)
                if event.valid?
                   event.save!
                    render json: @event, status: :created
                else
                    render json: {errors: @event.errors}, status: :unprocessable_entity
                end
        else
            render json: "Unregistered application", status: :unprocessable_entity
        end
    end
    

private
    
    def event_params
        params.require(:event).permit(:name)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
    before_action :authenticate_user!
    
    def index
   	    @registered_applications = RegisteredApplication.all
    end
    
    def show
        @user = User.find(params[:user_id])
        @registered_application = RegisteredApplication.find(params[:id])
        @events = @registered_application.events.group_by(&:name)
    end

    def new
        @user = User.find(params[:user_id])
        @registered_applications = RegisteredApplication.new
    end
    
    def create
        @user = User.find(params[:user_id])
        @registered_application = @user.registered_applications.new(app_params)
        @registered_application.user = current_user
        @new_app = RegisteredApplication.new
    
        if @registered_application.save
            flash[:notice] = "App was registered successfully."
        else
            flash.now[:alert] = "There was an error registering the applicatoin. Please try again."
        end
        
        respond_to do |format|
            format.html
            format.js
        end
    end
    
    def edit
        @registered_application = RegisteredApplication.find(params[:id])
    end
    
    def update
        @user = User.find(params[:user_id])
        @registered_application = RegisteredApplication.find(params[:id])
        @registered_application.assign_attributes(app_params)
        
    
        if @registered_application.save
            flash[:notice] = "App was updated successfully."
            redirect_to current_user
        else
            flash.now[:alert] = "There was an error registering the applicatoin. Please try again."
            
        end
        
    end
    
    def destroy
        @user = User.find(params[:user_id])
        @registered_application = @user.registered_applications.find(params[:id])
     
        if @registered_application.destroy
            flash[:notice] = "\"#{@registered_application.name}\" was removed successfully."
        else
            flash.now[:alert] = "There was an error removing the registered application."
        end
        
        respond_to do |format|
    		format.html
    		format.js 
    	end
    end
    
    
    private
    
    def app_params
        params.require(:registered_application).permit(:name, :url)
    end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, except: [:show]
    
    def show
		@user = User.find(params[:id] || current_user.id)
		@registered_applications = @user.registered_applications
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to user_path(current_user) if current_user
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="row">
                        <% if user_signed_in? %>
                        <div class="col-md-3 ">
                              <ul class="nav-pills nav-justified nav ">
                                  <li><%= link_to "Edit User-Info", edit_user_registration_path %></li>
                              </ul>
                        </div>
                        <div class="col-md-6">
                            <ul class="nav-tabs nav-justified nav">
                                <li><%= link_to "Apps To Track", welcome_index_path %></li>
                                <li><%= link_to "About", welcome_about_path %></li>
                            </ul>
                        </div>
                        <div class="col-md-3">
                            <div class="nav nav-justified">
                                    <p class="navbar-text navbar-right">Signed in as: <strong><%= current_user.username %></strong> | <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></p>
                            </div>
                        </div>
                        
                        <% else %>
                        <div class="col-md-6 col-md-offset-3">
                            <ul class="nav-tabs nav-justified nav">
                                <li><%= link_to "Blocmetrics", welcome_index_path %></li>
                                <li><%= link_to "About", welcome_about_path %></li>
                            </ul>
                        </div>
                        <div class="col-md-3 nav">
                            <div class="pull-right ">
                                <div class="btn-group" role="group" aria-label="...">
                                    <button type="button" class="btn btn-default"><%= link_to "Sign In", new_user_session_path %></button>
                                    <button type="button" class="btn btn-default"><%= link_to "Sign Up", new_user_registration_path %></button>
                                </div>
                            </div>
                        </div>
                        <% end %>
                    
                    </div>
                </div>
            </nav>
        </div>
    </div>
    
    <div class="flash">
       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash.now[:alert] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash.now[:alert] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
    </div>
   
    <%= yield %>
    
</div>
</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for [ user, registered_application ], remote: true do |f| %>

   
   <div class="row">
            <div class="field">
            <%= f.label :name %> :
            <%= f.text_field :name, class: 'form-control', placeholder: "Add name of application to register" %>
            </div>
            </br>
            <%= f.label :url %> :
        <div class="input-group">
            <%= f.text_field :url, class: "form-control", placeholder: "Add url of application  **include (https://)" %>
        <span class="input-group-btn">
            <%= f.submit "Add", class: 'btn btn-success' %>
        </span>
        </div>
<% end %> 

</div>

app/views/registered_applications/_registered_application.html.erb
<table class="table table-hover">
<%= content_tag :tr, class: 'text-justified', id: "registered_application-#{registered_application.id}" do %>
    <td class="text-left"><%= link_to "#{registered_application.name}", [ registered_application.user, registered_application ], method: :GET %> | 
    Events: <%= registered_application.events.count %> |
    <small><abbr title=<%="#{registered_application.url}"%> class="initialism"><%= link_to "Visit Site", "#{registered_application.url}", :target => "_blank" %></abbr></small></td>
    <td class="text-right"><%= link_to "Edit", edit_user_registered_application_path(registered_application.user, registered_application) %> |
    <%= link_to "De-register",[ registered_application.user, registered_application ], method: :delete, remote: true %></td>
<% end %>
</table>

app/views/registered_applications/create.js.erb
 <% if @registered_application.valid? %>
   $('.js-registered_applications').prepend("<%= escape_javascript(render(@registered_application)) %>");
   $('.new-app').html("<%= escape_javascript(render partial: 'registered_applications/form', locals: { user: @user, registered_application: @new_app }) %>");
   $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:notice] %></div>");
 <% else %>
   $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
   $('.new-app').html("<%= escape_javascript(render partial: 'registered_applications/form', locals: { user: @user, registered_application: @registered_application }) %>");
 <% end %>

app/views/registered_applications/destroy.js.erb
<% if @registered_application.destroyed? %>
    $('#registered_application-<%= @registered_application.id %>').hide();
    $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:notice] %></div>");
<% else %>
    $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/registered_applications/edit.html.erb
<h1 class="text-center">Edit <%="#{@registered_application.name}"%>'s info</h1>
 
 <div class="row">
   <div class="col-md-6 col-md-offset-3">
   <%= render partial: 'form', locals: { user: @registered_application.user, registered_application: @registered_application } %>
   </disv>
 </div>

app/views/registered_applications/new.html.erb
<h1>New Registered Application</h1>
    <div class="row">
       <div class='js-registered_applications'>
                <%= render @user.registered_applications %>
            </div>
        <div class="col-md-8">
            <%= render 'registered_applications/form', registered_application: RegisteredApplication.new, user: current_user  %>
        </div>
    </div>

app/views/registered_applications/show.html.erb
<div class="row">
    <div class="col-md-8.col-md-offset-2">
        <div class="media">
            <div class="media-body">
                <div class="page-header">
                    <h1 class="text-center"><small><%= link_to "Edit", edit_user_registered_application_path(@registered_application.user, @registered_application) %></small> | <%= "#{@registered_application.name}"%> | <small> <%= link_to "Visit Site", "https://#{@registered_application.url}", :target => "_blank" %></small></h1>
                    <h3 class="text-center"><%= "#{@registered_application.url}" %></h3>
                        <h4 class="text-center">
                            registered <%= time_ago_in_words(@registered_application.created_at) %> ago 
                        </h4>
                    </h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8.col-md-offset-2">
<% if @registered_application.events.count > 0 %>

        <h1 class="text-center">Events</h1>
            <div class="row">
                <%= pie_chart @registered_application.events.group(:name).count %>
            </div>
            <div class="row">
                <%= line_chart @registered_application.events.group_by_day(:created_at).count %>
            </div>
        </div>
    </div>
<% else %>
            <h1 class="text-center">No Events have occured for <%="#{@registered_application.name}"%></h1>
<% end %>
</div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
    <div class="row">
        <div class="col-md-8.col-md-offset-2">
            <div class="media">
                <div class="media-body">
                    <div class="page-header">
                        <h1 class="text-center"><%= current_user.username.capitalize! %>'s <small>Apps being tracked:</small></h1><br />
                    </div>
                    
                        <div class="col-md-8 col-md-offset-2">
                            
                                <div class='js-registered_applications'>
                                    
                                    <%= render @user.registered_applications %>
                                
                                </div>
                            
                        </div>
                        <% if current_user %>
                        <div class="col-md-6 col-md-offset-3">
                            <div class="new-app">
                                <%= render 'registered_applications/form', registered_application: RegisteredApplication.new , user: @user %>
                            </div>
                        </div>
                        <%end %>
    

                </div>
        
            </div>
        
        </div>
    
    </div>

app/views/welcome/about.html.erb
<div class="page-header">
  <h1>Blocmetrics<small> an analytics service to track events on websites.</small></h1>
</div>
<div class="well well-sm">Created as a portfolio-project by Bloc-Student: Josh Van Wyk and Bloc-Mentor: Mark Carpenter.</div>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
    <h1>Blocmetrics</br><small>You may already know of a good analytic service...</br>but this is a better one.</small></h1>

    </br>
    <p>
     <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
    </p>
</div>